CREATE TABLE Publishers(
	Id INT PRIMARY KEY AUTO_INCREMENT,
	Name VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE ReadingStates(
	Id INT PRIMARY KEY AUTO_INCREMENT,
	State VARCHAR(15) NOT NULL UNIQUE
);

CREATE TABLE Ranks(
	Id INT PRIMARY KEY AUTO_INCREMENT,
	Rank VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE Genres(
	Id INT PRIMARY KEY AUTO_INCREMENT,
	Genre VARCHAR(15) NOT NULL UNIQUE
);

CREATE TABLE Books(
	No INT PRIMARY KEY AUTO_INCREMENT,
	Name VARCHAR(50) NOT NULL,
	Url VARCHAR(200) NOT NULL,
	PublisherId INT NOT NULL,
	Price INT NOT NULL,
	ParchaseDate DATE NOT NULL,
	ReadingStateId INT NOT NULL,
	Comment TEXT NOT NULL,
	RankId INT NOT NULL,
	FOREIGN KEY(PublisherId) REFERENCES Publishers(Id),
	FOREIGN KEY(ReadingStateId) REFERENCES ReadingStates(Id),
	FOREIGN KEY(RankId) REFERENCES Ranks(Id)
);